version: '3'
services:
    rabbitmq01:
        image: rabbitmq:3.8-management
        container_name: rabbitmq01
        ports:
          - "15672"
          - "5672"
        hostname: rabbitmq01
        environment:
          - RABBITMQ_DEFAULT_USER=root
          - RABBITMQ_DEFAULT_PASS=admin
          - RABBITMQ_ERLANG_COOKIE=Rabbitmq@cluster
        volumes:
          - ./data/rabbitmq01:/var/lib/rabbitmq

    rabbitmq02:
        image: rabbitmq:3.8-management
        container_name: rabbitmq02
        ports:
          - "15672"
          - "5672"
        hostname: rabbitmq02
        environment:
          - RABBITMQ_DEFAULT_USER=root
          - RABBITMQ_DEFAULT_PASS=admin
          - RABBITMQ_ERLANG_COOKIE=Rabbitmq@cluster
        volumes:
          - ./data/rabbitmq02:/var/lib/rabbitmq

    rabbitmq03:
        image: rabbitmq:3.8-management
        container_name: rabbitmq03
        ports:
          - "15672"
          - "5672"
        hostname: rabbitmq03
        environment:
          - RABBITMQ_DEFAULT_USER=root
          - RABBITMQ_DEFAULT_PASS=admin
          - RABBITMQ_ERLANG_COOKIE=Rabbitmq@cluster
        volumes:
          - ./data/rabbitmq03:/var/lib/rabbitmq

    nginxrabbitmq:
        image: nginx:latest
        container_name: nginxrabbitmq
        #network_mode: host
        volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "5672:5672"
          - "15672:15672"
